reckless/data/urls.py
from data.views import SourceListView, SourceDetailView
from django.urls import path

app_name = 'data'
urlpatterns = [
    path('', SourceListView.as_view(), name='list'),
    path('<slug:slug>/', SourceDetailView.as_view(), name='detail'),
]

reckless/reckless/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from common import views

urlpatterns = [
    path('', views.home, name='home'),
    path('notes/', include('notes.urls')),
    path('data/', include('data.urls')),
    path('social/', include('social.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reckless/data/models.py
from django.db import models


class Source(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    description = models.TextField()
    file = models.FileField(upload_to='data/')
    created_on = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

reckless/data/views.py
from .models import Source
from django.views.generic import ListView, DetailView


class SourceListView(ListView):

    # set model
    model = Source
    ordering = ['title']


class SourceDetailView(DetailView):
    model = Source

reckless/data/templates/data/base.html
{% extends 'common/base.html' %}
{% block base_content %}
<section class="sidebar">
    <a class="active" href="{% url 'data:list' %}">All Data Sources</a>
</section>
<article class="content">
    {% block content %}Some stuff here{% endblock %}
</article>
{% endblock %}

reckless/data/templates/data/source_detail.html
{% extends 'data/base.html' %}

{% load markdown_extras %}

{% block content %}
<h1>{{ object.title }}</h1>
<p>{{ object.description | markdown | safe }}</p>
<p><a href="{{ object.file.url }}">Data File</a></p>
<p>Created On: {{ object.created_on|date }}</p>
{% endblock %}

reckless/data/templates/data/source_list.html
{% extends 'data/base.html' %}
{% block content %}
<h2>Data Sources</h2>
{% if object_list %}
<ul>
    {% for object in object_list %}
    <li><a href="{% url 'data:detail' object.slug %}">{{ object.title }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No data sources right now!</p>
{% endif %}
{% endblock %}