reckless/data/urls.py
from data.views import SourceListView, SourceDetailView
from django.urls import path

app_name = 'data'
urlpatterns = [
    path('', SourceListView.as_view(), name='list'),
    path('<slug:slug>/', SourceDetailView.as_view(), name='detail'),
]

reckless/reckless/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from common import views

urlpatterns = [
    path('', views.home, name='home'),
    path('notes/', include('notes.urls')),
    path('data/', include('data.urls')),
    path('social/', include('social.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reckless/social/urls.py
from social.views import HouseholdDetailView, PersonDetailView, index, NeighborhoodDetailView, \
    InteractionDetailView, InteractionListView, HouseholdUpdateView, HouseholdCreateView, \
    PersonCreateView, PersonListView, HouseholdListView, NeighborhoodListView, InteractionCreateView, \
    PersonUpdateView, NeighborhoodUpdateView, NeighborhoodCreateView, RelationshipDetailView, \
    RelationshipCreateView, InteractionUpdateView
from django.urls import path

app_name = 'social'
urlpatterns = [
    path('', index, name='index'),
    path('household/<int:pk>/', HouseholdDetailView.as_view(), name='household-detail'),
    path('households/', HouseholdListView.as_view(), name='household-list'),
    path('household/update/<int:pk>/', HouseholdUpdateView.as_view(), name='household-update'),
    path('household/create/', HouseholdCreateView.as_view(), name='household-create'),
    path('neighborhood/<int:pk>/', NeighborhoodDetailView.as_view(), name='neighborhood-detail'),
    path('neighborhoods/', NeighborhoodListView.as_view(), name='neighborhood-list'),
    path('neighborhood/update/<int:pk>/', NeighborhoodUpdateView.as_view(), name='neighborhood-update'),
    path('neighborhood/create/', NeighborhoodCreateView.as_view(), name='neighborhood-create'),
    path('interaction/<int:pk>/', InteractionDetailView.as_view(), name='interaction-detail'),
    path('interactions/', InteractionListView.as_view(), name='interaction-list'),
    path('interactions/tag/<slug:tag>/', InteractionListView.as_view(), name='interaction-tag-list'),
    path('interaction/create/', InteractionCreateView.as_view(), name='interaction-create'),
    path('interaction/update/<int:pk>/', InteractionUpdateView.as_view(), name='interaction-update'),
    path('interaction/interacted_person/<int:interacted_person_pk>/create/', InteractionCreateView.as_view(), name='interaction-with-interacted-person-create'),
    path('person/<int:pk>/', PersonDetailView.as_view(), name='person-detail'),
    path('people/', PersonListView.as_view(), name='person-list'),
    path('person/household/<int:household_pk>/create/', PersonCreateView.as_view(), name='person-with-household-create'),
    path('person/create/', PersonCreateView.as_view(), name='person-create'),
    path('person/update/<int:pk>/', PersonUpdateView.as_view(), name='person-update'),
    path('relationship/<int:pk>', RelationshipDetailView.as_view(), name='relationship-detail'),
    path('relationship/create/', RelationshipCreateView.as_view(), name='relationship-create'),
    path('relationship/person/<int:person_pk>/create/', RelationshipCreateView.as_view(), name='relationship-with-person-create'),
]

reckless/social/models.py
from django.contrib.gis.db import models
from taggit.managers import TaggableManager
import datetime
from django.core.exceptions import ValidationError

class Household(models.Model):
    name = models.CharField(max_length=100, blank=False)
    street_address = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    zip_code = models.CharField(max_length=10, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    neighborhood = models.ForeignKey('Neighborhood', on_delete=models.CASCADE, blank=False, related_name='households')
    notes = models.TextField(blank=True)

    class Meta:
        ordering = ["name"]
    def __str__(self):
        return f'{self.name} in {self.neighborhood.name}'


class Neighborhood(models.Model):
    name = models.CharField(max_length=100, blank=False)
    location = models.PointField(null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

class Person(models.Model):

    MALE = 'M'
    FEMALE = 'F'
    OTHER = 'O'
    SEX_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (OTHER, 'Other')
    ]

    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    f3_name = models.CharField(max_length=100, blank=True)
    household = models.ForeignKey('Household', on_delete=models.CASCADE, blank=False, related_name='people')
    birthdate = models.DateField(blank=True, null=True)
    notes = models.TextField(blank=True)
    is_me = models.BooleanField(default=False, blank=False)
    sex = models.CharField(max_length=1, choices=SEX_CHOICES, default=MALE, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def __str__(self):
        # Use a list comprehension to filter out blank fields, then join them with spaces
        return ' '.join([name for name in [self.first_name, self.f3_name, self.last_name] if name])

    def clean(self):
        # Check if at least one of first_name, last_name, and f3_name is present
        if not (self.first_name or self.last_name or self.f3_name):
            raise ValidationError('At least one of first_name, last_name, or f3_name must be provided.')

    def save(self, *args, **kwargs):
        self.clean()
        super(Person, self).save(*args, **kwargs)


class Relationship(models.Model):

    class Category(models.IntegerChoices):
        PARENT = 1
        CHILD = 2
        GRANDPARENT = 3
        GRANDCHILD = 4
        STEPCHILD = 5
        STEPPARENT = 6
        COWORKER = 7
        FRIEND = 8
        CLASSMATE = 9
        SPOUSE = 10
        SIGNIFICANT_OTHER = 11
        STUDENT = 12
        TEACHER = 13
        SIBLING = 14

    person = models.ForeignKey('Person', on_delete=models.CASCADE, blank=False, related_name='related_from_persons')
    related_person = models.ForeignKey('Person', on_delete=models.CASCADE, blank=False, related_name='related_to_persons')
    relationship_category = models.IntegerField(choices=Category.choices, default=Category.FRIEND, blank=False)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.related_person} is {self.person}\'s {self.get_relationship_category_display()}'


class Interaction(models.Model):
    person = models.ForeignKey('Person', on_delete=models.CASCADE, related_name='interacted_by_persons')
    interacted_people = models.ManyToManyField('Person', related_name='interacted_with_people')
    notes = models.TextField(blank=True)
    tags = TaggableManager()
    approximate_location = models.PointField(null=True)
    occurred_at = models.DateField(default=datetime.date.today)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-occurred_at"]
    def __str__(self):
        interacted_people_list = ", ".join(str(person) for person in self.interacted_people.all())
        return f"{self.person} interacted with {interacted_people_list} on {self.occurred_at} [{self.joined_tags()}]"
    def joined_tags(self):
        return ",".join(self.tags.names())

reckless/social/views.py
from django.shortcuts import render, get_object_or_404
from .models import Household, Person, Neighborhood, Interaction, Relationship
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.db.models import Q

def index(request):

    context = {
        'households': Household.objects.all(),
        'neighborhoods': Neighborhood.objects.all(),
        'interactions': Interaction.objects.order_by('-created_at'),
        'interaction_tags': Interaction.tags.most_common(),
    }

    return render(request, 'social/index.html', context)


class HouseholdListView(ListView):

    # set model
    model = Household
    ordering = ['name']


class HouseholdDetailView(DetailView):

    # set model
    model = Household

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        household = self.object
        people = household.people.all()

        relationships = []
        interaction_dict = {}
        for person in people:
            relationships.extend(person.related_from_persons.all())
            for interaction in Interaction.objects.filter(Q(person=person) | Q(interacted_people=person)):
                interaction_dict[interaction.pk] = interaction


        context['relationships'] = relationships
        context['interactions'] = list(interaction_dict.values())
        return context


class HouseholdUpdateView(LoginRequiredMixin, UpdateView):
    model = Household
    fields = [
        'name', 'street_address', 'city',
        'state', 'zip_code', 'neighborhood',
        'notes'
    ]
    success_url = "/household/{pk}/"
    login_url = '/admin/'


class HouseholdCreateView(LoginRequiredMixin, CreateView):
    model = Household
    fields = [
        'name', 'street_address', 'city',
        'state', 'zip_code', 'neighborhood',
        'notes'
    ]
    login_url = '/admin/'

    def get_success_url(self):
        return reverse('social:household-detail', kwargs={'pk': self.object.id})



class PersonDetailView(DetailView):

    model = Person

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        person = self.get_object()
        interactions = Interaction.objects.filter(Q(person=person) | Q(interacted_people=person)).distinct()
        context['interactions'] = interactions
        return context


class PersonListView(ListView):
    # set model
    model = Person
    ordering = ['last_name', 'first_name']


class PersonCreateView(LoginRequiredMixin, CreateView):
    model = Person
    fields = [
        'first_name', 'last_name', 'f3_name', 'household',
        'birthdate', 'is_me', 'sex',
        'notes'
    ]
    login_url = '/admin/'

    def get_initial(self):
        household_pk = self.kwargs.get('household_pk')
        if household_pk is None:
            initial = {}
        else:
            initial = {'household': household_pk}
        return initial

    def get_success_url(self):
        return reverse('social:person-detail', kwargs={'pk': self.object.id})


class PersonUpdateView(LoginRequiredMixin, UpdateView):
    model = Person
    fields = [
        'first_name', 'last_name', 'f3_name', 'household',
        'birthdate', 'is_me', 'sex',
        'notes'
    ]
    success_url = "/person/list/"
    login_url = '/admin/'

    def get_success_url(self):
        return reverse('social:person-detail', kwargs={'pk': self.object.id})
class NeighborhoodDetailView(DetailView):

    # set model
    model = Neighborhood


class NeighborhoodListView(ListView):

    # set model
    model = Neighborhood
    ordering = ['name']


class NeighborhoodUpdateView(LoginRequiredMixin, UpdateView):
    model = Neighborhood
    fields = [
        'name'
    ]
    success_url = "/neighborhood/all"
    login_url = '/admin/'

    def get_success_url(self):
        return reverse('social:neighborhood-detail', kwargs={'pk': self.object.id})


class NeighborhoodCreateView(LoginRequiredMixin, CreateView):
    model = Neighborhood
    fields = [
        'name'
    ]
    success_url = "/neighborhood/all"
    login_url = '/admin/'

    def get_success_url(self):
        return reverse('social:neighborhood-detail', kwargs={'pk': self.object.id})


class InteractionDetailView(DetailView):

    model = Interaction


class InteractionListView(ListView):

    # set model
    model = Interaction
    ordering = ['-updated_on']

    def get_queryset(self):

        # filter tags if provided
        if 'tag' in self.kwargs:
            return Interaction.objects.filter(tags__slug__in=[self.kwargs['tag']])
        else:
            return Interaction.objects.all()

class InteractionCreateView(LoginRequiredMixin, CreateView):
    model = Interaction
    fields = [
        'person', 'interacted_people', 'notes',
        'tags', 'occurred_at'
    ]
    login_url = '/admin/'

    def get_initial(self):
        me = Person.objects.filter(is_me=True).first()
        interacted_person_pk = self.kwargs.get('interacted_person_pk')

        initial = {}
        if me is not None:
            initial['person'] = me.id
        if interacted_person_pk is not None:
            person = get_object_or_404(Person, id=interacted_person_pk)
            initial['interacted_people'] = [person]

        return initial

    def get_success_url(self):
        return reverse('social:interaction-detail', kwargs={'pk': self.object.id})

class InteractionUpdateView(LoginRequiredMixin, UpdateView):
    model = Interaction
    fields = [
        'person', 'interacted_people', 'notes',
        'tags', 'occurred_at'
    ]
    login_url = '/admin/'

    def get_success_url(self):
        return reverse('social:interaction-detail', kwargs={'pk': self.object.id})

class RelationshipDetailView(DetailView):

    # set model
    model = Relationship

class RelationshipCreateView(LoginRequiredMixin, CreateView):
    model = Relationship
    fields = [
        'person', 'related_person', 'relationship_category', 'notes'
    ]
    success_url = ""
    login_url = '/admin/'

    def get_initial(self):

        person_pk = self.kwargs.get('person_pk')

        initial = {}
        if person_pk is not None:
            person = get_object_or_404(Person, id=person_pk)
            initial['person'] = person

        return initial

    def get_success_url(self):
        return reverse('social:relationship-detail', kwargs={'pk': self.object.id})

reckless/social/templates/social/base.html
{% extends 'common/base.html' %}
{% block base_content %}
<section class="sidebar">
    <a href="{% url 'social:household-list' %}">Households</a>
    <a href="{% url 'social:neighborhood-list' %}">Neighborhoods</a>
    <a href="{% url 'social:person-list' %}">People</a>
    <a href="{% url 'social:interaction-list' %}">Interaction</a>
</section>
<article class="content">
    {% block content %}Social stuff here{% endblock %}
</article>
{% endblock %}

reckless/social/templates/social/household_detail.html
{% extends 'social/base.html' %}

{% block content %}

    <h1>{{ object }}</h1>
    <h2>People</h2>

    <ul>
        {% for person in object.people.all|dictsort:"last_name"|dictsort:"first_name" %}
        <li><a href="{% url 'social:person-detail' person.id %}">{{ person }}</a></li>
        {% endfor %}
        <li><a href="{% url 'social:person-with-household-create' object.pk %}">Add New Family Member</a></li>
    </ul>

    <h2>Relationships</h2>
        <ul>
            {% for relationship in relationships %}
            <li><a href="{% url 'social:relationship-detail' relationship.pk %}">{{ relationship }}</a></li>
            {% endfor %}
            <li><a href="{% url 'social:relationship-create' %}">Add a relationship</a></li>
        </ul>

    <h2>Interactions</h2>
        <ul>
            {% for interaction in interactions %}
            <li><a href="{% url 'social:interaction-detail' interaction.pk %}">{{ interaction }}</a></li>
            {% endfor %}
            <li><a href="{% url 'social:interaction-create' %}">Add an interaction</a></li>
        </ul>
    <h2>Notes</h2>
    <p>{{ object.notes }}</p>
<p>Created On: {{ object.created_at|date }}</p>
<p>Updated On: {{ object.updated_at|date }}</p>
<p><a href="{% url 'social:household-update' object.pk %}">Update Me</a></p>
{% endblock %}

reckless/social/templates/social/household_list.html
{% extends 'social/base.html' %}
{% block content %}
<h2>Notes</h2>
{% if object_list %}
<ul>
    {% for household in object_list %}
    <li><a href="{% url 'social:household-detail' household.pk %}">{{ household.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No households right now!</p>
{% endif %}
<p><a href="{% url 'social:household-create' %}">Add a household</a></p>
{% endblock %}

reckless/social/templates/social/index.html
{% extends 'social/base.html' %}

{% block content %}

<h1>Households</h1>
{% for household in households %}
<li><a href="{% url 'social:household-detail' household.pk %}">{{ household.name }}</a></li>
{% endfor %}
<li><a href="{% url 'social:household-create' %}">Add New</a></li>
<h1>Neighborhoods</h1>
{% for neighborhood in neighborhoods %}
<li><a href="{% url 'social:neighborhood-detail' neighborhood.pk %}">{{ neighborhood.name }}</a></li>
{% endfor %}
<h1>Latest Interactions</h1>
{% for interaction in interactions %}
<li><a href="{% url 'social:interaction-detail' interaction.pk %}">{{ interaction }}</a></li>
{% endfor %}
<h2>Interaction Tags</h2>
{% for interaction_tag in interaction_tags %}
<li><a href="{% url 'social:interaction-tag-list' interaction_tag.slug %}">{{ interaction_tag.name }}</a></li>
{% endfor %}
{% endblock %}

reckless/social/templates/social/interaction_detail.html
{% extends 'social/base.html' %}

{% block content %}
<h1>{{ object }}</h1>
    <h2>People</h2>
    <ul>
    <li><a href="{% url 'social:person-detail' object.person.pk %}">{{ object.person }}</a> (person who did interacting)</li>
    {% for person in object.interacted_people.all %}
        <li><a href="{% url 'social:person-detail' person.pk %}">{{ person }}</a></li>
    {% endfor %}
    </ul>
    <h2>Tags</h2>
    <ul>
    {% for tag in object.tags.all %}
    <li><a href="{% url 'social:interaction-tag-list' tag %}">{{ tag.name }}</a></li>
    {% endfor %}
    </ul>
<h2>Notes</h2>
<p>{{ object.notes }}</p>
<p>Created On: {{ object.created_at|date }}</p>
<p>Updated On: {{ object.updated_at|date }}</p>
<p><a href="{% url 'social:interaction-update' object.pk %}">Update Me</a></p>
{% endblock %}

reckless/social/templates/social/interaction_form.html
{% extends 'social/base.html' %}
{% load crispy_forms_tags %}
{% block extra_head %} {{ form.media }} {% endblock %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

reckless/social/templates/social/interaction_list.html
{% extends 'social/base.html' %}
{% block content %}
<h2>Interactions</h2>
{% if object_list %}
<ul>
    {% for interaction in object_list %}
    <li><a href="{% url 'social:interaction-detail' interaction.pk %}">{{ interaction }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No interactions right now!</p>
{% endif %}
<p><a href="{% url 'social:interaction-create' %}">Add an interaction</a></p>
{% endblock %}

reckless/social/templates/social/neighborhood_detail.html
{% extends 'social/base.html' %}

{% block content %}
<h1>{{ object.name }}</h1>

<h2>Households in Neighborhood</h2>
<ul>
{% for household in object.households.all %}
    <li><a href="{% url 'social:household-detail' household.pk %}">{{ household.name }}</a></li>
{% endfor %}
</ul>
<p><a href="{% url 'social:neighborhood-update' object.pk %}">Update Me</a></p>
{% endblock %}

reckless/social/templates/social/neighborhood_form.html
{% extends 'social/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

reckless/social/templates/social/neighborhood_list.html
{% extends 'social/base.html' %}
{% block content %}
<h2>Notes</h2>
{% if object_list %}
<ul>
    {% for neighborhood in object_list %}
    <li><a href="{% url 'social:neighborhood-detail' neighborhood.pk %}">{{ neighborhood.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No neighborhoods right now!</p>
{% endif %}
<p><a href="{% url 'social:neighborhood-create' %}">Add a neighborhood</a></p>
{% endblock %}

reckless/social/templates/social/person_detail.html
{% extends 'social/base.html' %}

{% block content %}
    <h1>{{ object.first_name }} {{ object.last_name }}</h1>
    <h2>Household</h2>
    <p><a href="{% url 'social:household-detail' object.household.pk %}">{{ object.household }}</a></p>
    <h2>Relationships</h2>
    <ul>
        {% for relationship in object.related_from_persons.all %}
            <li><a href="{% url 'social:person-detail' relationship.related_person.pk %}">{{ relationship }}</a></li>
        {% endfor %}
        {% for relationship in object.related_to_persons.all %}
            <li><a href="{% url 'social:person-detail' relationship.person.pk %}">{{ relationship }}</a></li>
        {% endfor %}
        <li><a href="{% url 'social:relationship-with-person-create' object.pk %}">Add Relationship</a></li>
    </ul>
    <h2>Interactions</h2>
    <ul>
        {% for interaction in interactions|dictsortreversed:'updated_at' %}
            <li><a href="{% url 'social:interaction-detail' interaction.pk %}">{{ interaction }}</a></li>
        {% endfor %}
        <li><a href="{% url 'social:interaction-with-interacted-person-create' object.pk %}">Add Interaction</a></li>
    </ul>
    <p>Created On: {{ object.created_at|date }}</p>
    <p>Updated On: {{ object.updated_at|date }}</p>
    <p><a href="{% url 'social:person-update' object.id %}">Update Me</a></p>
{% endblock %}

reckless/social/templates/social/person_form.html
{% extends 'social/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

reckless/social/templates/social/person_list.html
{% extends 'social/base.html' %}
{% block content %}
<h2>People</h2>
{% if object_list %}
<ul>
    {% for person in object_list %}
    <li><a href="{% url 'social:person-detail' person.pk %}">{{ person.last_name }}, {{ person.first_name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No people right now!</p>
{% endif %}
<p><a href="{% url 'social:person-create' %}">Add</a> a person</p>
{% endblock %}

reckless/social/templates/social/relationship_detail.html
{% extends 'social/base.html' %}

{% block content %}
<h1>{{ object }}</h1>
<h2>Notes</h2>
<p>{{ object.notes }}</p>
<p>Created On: {{ object.created_at|date }}</p>
<p>Updated On: {{ object.updated_at|date }}</p>
<p><a href="#">Update Me</a></p>
{% endblock %}