reckless/data/urls.py
from data.views import SourceListView, SourceDetailView
from django.urls import path

app_name = 'data'
urlpatterns = [
    path('', SourceListView.as_view(), name='list'),
    path('<slug:slug>/', SourceDetailView.as_view(), name='detail'),
]

reckless/notes/urls.py
from notes.views import NoteListView, NoteCreateView, NoteDetailView, NoteUpdateView
from django.urls import path

app_name = 'notes'
urlpatterns = [
    path('', NoteListView.as_view(), name='list'),
    path('add/', NoteCreateView.as_view(), name='add'),
    path('<slug:slug>/', NoteDetailView.as_view(), name='detail'),
    path('update/<slug:slug>/', NoteUpdateView.as_view(), name='update'),
    path('tag/<slug:tag>/', NoteListView.as_view(), name='tag-list')
]

reckless/reckless/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from common import views

urlpatterns = [
    path('', views.home, name='home'),
    path('notes/', include('notes.urls')),
    path('data/', include('data.urls')),
    path('social/', include('social.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reckless/social/urls.py
from social.views import HouseholdDetailView, PersonDetailView, index, NeighborhoodDetailView, \
    InteractionDetailView, InteractionListView, HouseholdUpdateView, HouseholdCreateView, \
    PersonCreateView, PersonListView, HouseholdListView, NeighborhoodListView, InteractionCreateView, \
    PersonUpdateView, NeighborhoodUpdateView, NeighborhoodCreateView, RelationshipDetailView, \
    RelationshipCreateView, InteractionUpdateView
from django.urls import path

app_name = 'social'
urlpatterns = [
    path('', index, name='index'),
    path('household/<int:pk>/', HouseholdDetailView.as_view(), name='household-detail'),
    path('households/', HouseholdListView.as_view(), name='household-list'),
    path('household/update/<int:pk>/', HouseholdUpdateView.as_view(), name='household-update'),
    path('household/create/', HouseholdCreateView.as_view(), name='household-create'),
    path('neighborhood/<int:pk>/', NeighborhoodDetailView.as_view(), name='neighborhood-detail'),
    path('neighborhoods/', NeighborhoodListView.as_view(), name='neighborhood-list'),
    path('neighborhood/update/<int:pk>/', NeighborhoodUpdateView.as_view(), name='neighborhood-update'),
    path('neighborhood/create/', NeighborhoodCreateView.as_view(), name='neighborhood-create'),
    path('interaction/<int:pk>/', InteractionDetailView.as_view(), name='interaction-detail'),
    path('interactions/', InteractionListView.as_view(), name='interaction-list'),
    path('interactions/tag/<slug:tag>/', InteractionListView.as_view(), name='interaction-tag-list'),
    path('interaction/create/', InteractionCreateView.as_view(), name='interaction-create'),
    path('interaction/update/<int:pk>/', InteractionUpdateView.as_view(), name='interaction-update'),
    path('interaction/interacted_person/<int:interacted_person_pk>/create/', InteractionCreateView.as_view(), name='interaction-with-interacted-person-create'),
    path('person/<int:pk>/', PersonDetailView.as_view(), name='person-detail'),
    path('people/', PersonListView.as_view(), name='person-list'),
    path('person/household/<int:household_pk>/create/', PersonCreateView.as_view(), name='person-with-household-create'),
    path('person/create/', PersonCreateView.as_view(), name='person-create'),
    path('person/update/<int:pk>/', PersonUpdateView.as_view(), name='person-update'),
    path('relationship/<int:pk>', RelationshipDetailView.as_view(), name='relationship-detail'),
    path('relationship/create/', RelationshipCreateView.as_view(), name='relationship-create'),
    path('relationship/person/<int:person_pk>/create/', RelationshipCreateView.as_view(), name='relationship-with-person-create'),
]

reckless/common/models.py
from django.db import models

# Create your models here.

reckless/common/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'common/home.html')

reckless/common/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Reckless Analysis</title>
    <link rel="stylesheet" type="text/css" href="{% static 'common/base.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Overpass:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    {% block extra_head %}{% endblock %}
    <style>
    {% block extra_style %}{% endblock %}
    </style>

  </head>
  <body>

    <header class="header">
      <a href="{% url 'home' %}" class="brand">Reckless Analysis</a>
      <nav class="topnav">
        <a href="#news">Blog</a>
        <a href="{% url 'data:list' %}">Data</a>
        {% if user.is_authenticated %}
        <a href="{% url 'social:index' %}">Social</a>
        <a href="{% url 'notes:list' %}">Notes</a>
        <a href="{% url 'admin:index' %}">Admin</a>
        {% else %}
        <a href="{% url 'admin:index' %}">Login</a>
        {% endif %}
      </nav>

    </header>

    <section class="main">
      {% block base_content %}<h2>Top Navigation Example</h2><p>Some content..</p>{% endblock %}
    </section>

  </body>
</html>

reckless/common/templates/common/home.html
{% extends 'common/base.html' %}
{% block base_content %}
<h2> Welcome to Reckless Analysis!</h2>
{% endblock %}