reckless/data/urls.py
from data.views import SourceListView, SourceDetailView
from django.urls import path

app_name = 'data'
urlpatterns = [
    path('', SourceListView.as_view(), name='list'),
    path('<slug:slug>/', SourceDetailView.as_view(), name='detail'),
]

reckless/notes/urls.py
from notes.views import NoteListView, NoteCreateView, NoteDetailView, NoteUpdateView
from django.urls import path

app_name = 'notes'
urlpatterns = [
    path('', NoteListView.as_view(), name='list'),
    path('add/', NoteCreateView.as_view(), name='add'),
    path('<slug:slug>/', NoteDetailView.as_view(), name='detail'),
    path('update/<slug:slug>/', NoteUpdateView.as_view(), name='update'),
    path('tag/<slug:tag>/', NoteListView.as_view(), name='tag-list')
]

reckless/reckless/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from common import views

urlpatterns = [
    path('', views.home, name='home'),
    path('notes/', include('notes.urls')),
    path('data/', include('data.urls')),
    path('social/', include('social.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reckless/notes/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class Note(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    content = models.TextField()
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notes')
    tags = TaggableManager()

reckless/notes/views.py
from django.shortcuts import render
from .models import Note
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

class NoteListView(ListView):

    # set model
    model = Note
    ordering = ['-updated_on']

    def get_queryset(self):

        # filter tags if provided
        if 'tag' in self.kwargs:
            return Note.objects.filter(tags__slug__in=[self.kwargs['tag']])
        else:
            return Note.objects.all()


class NoteCreateView(LoginRequiredMixin, CreateView):
    model = Note
    fields = ['title', 'slug', 'content', 'tags', 'author']
    success_url = "/notes/{slug}/"
    login_url = '/admin/'

    def get_initial(self):
        initial = {'author': self.request.user}
        return initial


class NoteUpdateView(LoginRequiredMixin, UpdateView):
    model = Note
    fields = ['title', 'slug', 'content', 'tags', 'author']
    success_url = "/notes/{slug}/"
    login_url = '/admin/'


class NoteDetailView(DetailView):
    model = Note

reckless/notes/templates/notes/base.html
{% extends 'common/base.html' %}
{% block base_content %}
<section class="sidebar">
    <a class="active" href="{% url 'notes:list' %}">All Notes</a>
    {% for tag in common_tags %}
    <a href="#">{{ tag.name }}</a>
    {% endfor %}
</section>
<article class="content">
    {% block content %}Some stuff here{% endblock %}
</article>
{% endblock %}

reckless/notes/templates/notes/note_detail.html
{% extends 'notes/base.html' %}

{% load markdown_extras %}

{% block content %}
<h1>{{ object.title }}</h1>
<p>{{ object.content | markdown | safe }}</p>
<p>Tags: {{object.tags.all|join:", "}}</p>
<p>Created By: {{ object.author }}</p>
<p>Created On: {{ object.created_on|date }}</p>
<p>Updated On: {{ object.updated_on|date }}</p>
<p><a href="{% url 'notes:update' object.slug %}">Update Me</a></p>
{% endblock %}

reckless/notes/templates/notes/note_form.html
{% extends 'notes/base.html' %}
{% load crispy_forms_tags %}
{% block extra_style %}
textarea.textarea {
    width: 900px;
    height: 400px;
}
{% endblock extra_style %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

reckless/notes/templates/notes/note_list.html
{% extends 'notes/base.html' %}
{% block content %}
<h2>Notes</h2>
{% if object_list %}
<ul>
    {% for note in object_list %}
    <li><a href="{% url 'notes:detail' note.slug %}">{{ note.title }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No notes right now!</p>
{% endif %}
<p><a href="{% url 'notes:add' %}">Add</a> a note</p>
{% endblock %}